### PR TITLE
Use new Sockethub IRC connect flow, show connect errors

### LINKED ISSUE #194: Test server config/connection before creating/saving a new account
Validate that the config actually results in a successful connection before adding the space to both RS and the UI.

* [x] XMPP
* [x] IRC

refs #192

### PR DESCRIPTION
**Pull request by raucao**
Implements and relies on https://github.com/sockethub/sockethub/pull/671

closes #194

### CODE REVIEW

**Comment by raucao** [comment]
@silverbucket For some reason, the yarn build is failing with Sockethub master now:

    The command "yarn run build" failed and exited with 127 during .

**Comment by raucao** [comment]
I have found the problem. For some reason, the standard `yarn install` in sockethub's root `package.json` does not run the lerna bootstrap/install anymore. I changed it to the new npm script, but I think this is less clean and intuitive than a standard `yarn install && yarn start`.

**Comment by silverbucket** [comment]
@raucao yeah, unfortunately this is a limitation of `lerna` when there is a package.json in the root of the repository (in additon to each packages package.json). I created an issue here explaining it https://github.com/lerna/lerna/issues/3070, in the meantime we're going to have to use `yarn deps` as the one-step command to install all dependencies.

**Review by silverbucket — APPROVED** [review]
LGTM

**Pull request merged**
