### PR TITLE
Fix archive loading for today's logs

### LINKED ISSUE #89: Hyperchannel loads logs from previous day, but not current one
Currently, on app startup, Hyperchannel will load logs of the previous day (with content), but not the current one. Not sure if it's always or in certain situations, but I could reproduce it in the middle of (GMT) day today, so it doesn't seem to be some local-timezone issue or similar.

### PR DESCRIPTION
**Pull request by galfert**
Paired with @skddc on this.

Fixes #89

Rename some variables to make a little more sense and use UTC dates everywhere.

### CODE REVIEW

**Comment by skddc** [comment]
Unfortunately, now it's skipping one day when going back from today's history. Looks like we still need to find out why the actual skip happened within UTC time.

**Comment by galfert** [comment]
Dang :(

Will try to have another look at it later.

**Comment by galfert** [comment]
Ok, now it should finally all work.

**Comment by skddc** [comment]
Yup, all looking great now.

**Pull request merged**
