### PR TITLE
Change username when getting update event from Sockethub

### LINKED ISSUE #108: Handle username updates
When a username is already taken, Sockethub sends an `update` message with a new username that was assigned instead.

### PR DESCRIPTION
**Pull request by galfert**
Closes #108

### CODE REVIEW

**Comment by skddc** [comment]
Weird, for me it uses the protected username now (instead of the new one):

screenshot from 2017-05-08 17-58-59

**Comment by galfert** [comment]
Weird.

I can't test this right now anymore with my current Sockethub version. Would be great if we could merge #113 first, then I will rebase this PR on master and see what's up.

**Comment by galfert** [comment]
Judging from the screenshot I think you weren't really connected, because I don't see those messages you wrote in my logs. My guess is that was due to the Sockethub issues/incompatibilities we fixed today.

I updated this branch with the recent changes in master and for me the name change worked as expected just now.

**Comment by skddc** [comment]
Ok, makes sense. Thanks. Trying it again.

**Comment by skddc** [comment]
w00t!

**Pull request merged**
