### PR TITLE
Update Ember and octanify all the things

### LINKED ISSUE #184: Upgrade codebase to Ember Octane
We can do this bit by bit, because Octane (introduced in Ember 3.15) is backward-compatible with classic Ember features. It'll just throw a ton of linter warnings, of course.

Here's a handy cheat sheet for all the changes: https://ember-learn.github.io/ember-octane-vs-classic-cheat-sheet/

### PR DESCRIPTION
**Pull request by galfert**
Closes #184 

This updates Ember to the latest stable version (3.17) and updates the whole codebase to use the latest and greatest of Ember Octane (e.g. native JS classes, decorators, angle bracket components, ...)

### CODE REVIEW

**Comment by skddc** [comment]
Wow, this one is *massive*. :eyes:

**Comment by skddc** [comment]
Everything regarding chat itself seems to be working perfectly fine. However, I get an exception when trying to add a space from a preset:

```
Error: Assertion Failed: You must pass a function as the `fn` helpers first argument, you passed saveSpace
```

I remember that I tried upgrading the settings to Octane and then gave up, because I couldn't make it work.

**Comment by galfert** [comment]
The error itself was pretty easy to fix. I hadn't tried that part of the app myself yet, so I found a few other mistakes and fixed those as well. Now it should at least work the same as before.

That doesn't prevent us from talking about your thoughts on better settings of course :)

**Comment by skddc** [comment]
OK, great!

**Comment by skddc** [comment]
5d15fca4_Screenshot from 2020-04-01 11-36-55

Hooray!

**Comment by skddc** [comment]
Missed one thing here still. ^^

**Pull request merged**
